- composer.json
- phpstan.neon
Signed-off-by: Jeroen v.d. Gulik <jeroen@isset.nl>
> Added PhpStan as dev dependancy

- composer.json
You need to manually install this if you want to use code generation.
> 🐛 Symfony YAML not installed.

- .php_cs
> Fix: Keep rules sorted

- docs/docs/README.md
- docs/docs/advanced/custom-repository.md
- docs/docs/advanced/message-decoration.md
- docs/docs/advanced/message-internals.md
- docs/docs/advanced/rebuilding-projections.md
- docs/docs/advanced/upcasting.md
- docs/docs/core-concepts.md
- docs/docs/event-sourcing.md
- docs/docs/getting-started/1-creating-an-aggregate-root.md
- docs/docs/getting-started/2-create-events-and-commands.md
- docs/docs/getting-started/4-bootstrap.md
- docs/docs/index.md
- docs/docs/lifecycle.md
- docs/docs/reacting-to-events/process-managers.md
- docs/docs/reacting-to-events/projections-and-read-models.md
- docs/docs/testing/handling-exception.md
- docs/docs/testing/index.md
- docs/docs/testing/setting-preconditions.md
- docs/docs/testing/testing-with-time.md
> Fix: Typos and wording

- docs/docs/getting-started/2-create-events-and-commands.md
first of all: Thank you for this awesome library!
Maybe I'm wrong but I noticed a code snippet with the old signature, here's the fix
> change the signature in the snippet to follow the new interface

- docs/docs/snapshotting/index.md
> Fix typo for snapshotting

- docs/docs/getting-started/1-creating-an-aggregate-root.md
When i played around with this package, this was not completely clear to me. So i tought it would be helpful to others if this was documented.
> [docs] Add section on how to apply events to the aggregate root

- docs/docs/getting-started/1-creating-an-aggregate-root.md
A code block wasn't terminated.
> Minor documentation improvement

- docs/docs/event-sourcing/1-creating-an-aggregate-root.md
PS: would you accept a PR that adds "Edit on GitHub" links on doc pages?
> Fix missing keyword & normalize code style

- src/AggregateAlwaysAppliesEvents.php
- src/AggregateAppliesKnownEvents.php
- src/AggregateRootBehaviour.php
- src/AggregateRootWithAggregates.php
- src/EventRecorder.php
- src/EventSourcedAggregate.php
- src/LibraryConsumptionTests/ComplexAggregates/CauseDelegatedBehavior.php
- src/LibraryConsumptionTests/ComplexAggregates/ComplexAggregateRoot.php
- src/LibraryConsumptionTests/ComplexAggregates/ComplexAggregateRootTest.php
- src/LibraryConsumptionTests/ComplexAggregates/DelegatedActionWasPerformed.php
- src/LibraryConsumptionTests/ComplexAggregates/DelegatedAggregateWasChosen.php
- src/LibraryConsumptionTests/ComplexAggregates/DelegatedAggregateWasDiscarded.php
- src/LibraryConsumptionTests/ComplexAggregates/DelegatedBehaviorInAggregate.php
This proposal PR introduces the capabilities needed to model complexer aggregate roots that contain event-sourced aggregates.
> Complex aggregate roots with inner aggregates

- docs/docs/testing/index.md
> Testing Docs: Missing word 

- composer.json
Same description as the website. I'll also update the repo description with this if that's okay for you.
> Update composer description

- README.md
Small proposal for a new header similar to the one from https://github.com/EventSaucePHP/LaravelEventSauce
Use the rich diff on the PR to see the before/after.
> New README header

- docs/docs/index.md
I'm also converting instances of "event-sourcing" to "event sourcing" for consistency. If this is not preferred, then we should update instances of "event sourcing" to "event-sourcing". :)
> Updating language to better convey intent

- composer.json
This will create a proper targetable 2.x version in Composer.
> Allow people to target ^2@dev and get the current WIP 2.x work

- docs/_data/menu.yml
- docs/docs/advanced/aggregate-root-with-aggregates.md
- src/LibraryConsumptionTests/AggregateWithDelegatedBehavior/AggregateRootWithDelegatedBehavior.php
- src/LibraryConsumptionTests/AggregateWithDelegatedBehavior/AggregateRootWithDelegatedBehaviorTest.php
- src/LibraryConsumptionTests/AggregateWithDelegatedBehavior/CauseDelegatedBehavior.php
- src/LibraryConsumptionTests/AggregateWithDelegatedBehavior/DelegatedActionWasPerformed.php
- src/LibraryConsumptionTests/AggregateWithDelegatedBehavior/DelegatedAggregateWasChosen.php
- src/LibraryConsumptionTests/AggregateWithDelegatedBehavior/DelegatedAggregateWasDiscarded.php
- src/LibraryConsumptionTests/AggregateWithDelegatedBehavior/DelegatedBehaviorInAggregate.php
This clears up the tests covering the aggregate with aggregates as well as adding some documentation describing the functionality.
> Fix ambiguous test aggregate partial

- docs/_data/menu.yml
- docs/docs/faq/index.md
Started with a simple FAQ chapter for now as I thought it does not make a lot of sense to already split this in subchapters etc.
We can still do that as the chapter grows :)
> Introducing the FAQ docs chapter

- docs/docs/faq/index.md
Hey Frank
Instead of opening another issue to see if my understanding of ES is correct, I thought I would document my question in our new FAQ section right away. So should you find the time to answer the question, I can directly capture the answer for everybody in the docs :)
> More FAQ entries

- docs/_data/menu.yml
My assumption is that this was replaced by Replaying Messages
> Remove missing doc from menu

- src/AggregateRoot.php
- src/AggregateRootBehaviour.php
This PR adds a template for the `aggregateRootId` property.
> Add template to AggregateRoot and AggregateRootBehaviour

- docs/docs/advanced/anti-corruption-layer.md
- src/TestUtilities/AntiCorruptionLayerTestCase.php
- src/TestUtilities/TestingAntiCorruptionLayers/AntiCorruptionLayerTest.php
- src/TestUtilities/TestingAntiCorruptionLayers/EventA.php
- src/TestUtilities/TestingAntiCorruptionLayers/EventB.php
Adds a testcase for anti corruption layers.
> Add anti corruption layer testcase

- .github/workflows/tests.yml
- composer.json
- src/AntiCorruptionLayer/AllowAllMessagesTest.php
- src/AntiCorruptionLayer/AllowMessagesWithPayloadOfTypeTest.php
- src/AntiCorruptionLayer/AntiCorruptionMessageConsumerTest.php
- src/AntiCorruptionLayer/AntiCorruptionMessageDispatcherTest.php
- src/AntiCorruptionLayer/AntiCorruptionMessageRelayTest.php
- src/AntiCorruptionLayer/MatchAllMessageFilterTest.php
- src/AntiCorruptionLayer/MatchAnyMessageFilterTest.php
- src/AntiCorruptionLayer/MessageTranslatorPerPayloadTypeTest.php
- src/AntiCorruptionLayer/NeverAllowMessagesTest.php
- src/CodeGeneration/CodeDumperTest.php
- src/CodeGeneration/YamlDefinitionLoaderTest.php
- src/MessageTest.php
- src/TestUtilities/composer.json
Adds phpunit 10 (https://phpunit.de/announcements/phpunit-10.html)
> add phpunit 10

- docs/docs/utilities/event-dispatcher.md
While reading, found a couple of things that caught my eye.
> Verbiage Fix: Event Dispatcher

- docs/docs/advanced/message-internals.md
> Fix typo in docs/advanced/message-internals

- src/Message.php
Add ability to provide generic AggregateRootId for Message.
> Add generic template for Message
