EventSaucePHP/EventSauce

- .php_cs
❗️ Blocked by #29.
This PR
Related to https://github.com/EventSaucePHP/EventSauce/pull/29/commits/d3fdbe96eaeaeb6d70ead6c59ff4c9c67920d04f.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/tree/v2.10.4#usage:
>**no_alias_functions** [`@Symfony:risky`]
>
>Master functions shall be used instead of aliases.
>
>Risky rule: risky when any of the alias functions are overridden.
> Enhancement: Enable no_alias_functions fixer

- docs/docs/event-sourcing.md
It feels better to leave this part out as the next header also doesn't explicitly has it. Either it's included or left out in both but anything else feels a bit off.
> Remove redundant wording in sub header

- src/AggregateRootRepository.php
- src/AggregateRootTestCase.php
- src/ConstructingAggregateRootRepository.php
This is an alternate implementation to achieve the same goal. In this implementation the aggregate root repository is converted into an interface and the default implementation is the `ConstructingAggregateRootRepository` which is a sane default implementation. This effectively turns the whole library into a reference implementation of itself.
> Fixes #28: extracted an interface from the aggregate root repository.

- docs/docs/advanced/database-structure.md
So it's inline with other examples throughout the EventSauce repos. This naming is also used in the Laravel extension.
> Use consistent event store table name

- src/EventConsumer.php
- src/Integration/EventConsumption/DummyEventForConsuming.php
- src/Integration/EventConsumption/EventConsumerStub.php
- src/Integration/EventConsumption/EventConsumerTest.php
This abstract class allows you to create handle methods that are payload specific. This prevents you from having to unwrap it in your consumer. For convenience the message instance itself is passed along as the second argument, in case you need the aggregate root ID or any other headers.
Example:
```php
<?php
use EventSauce\EventSourcing\EventConsumer;
class MyEventConsumer extends EventConsumer
{
public function handleSomeEvent(SomeEvent $event)
{
// handle the event.
}
}
```
> Feature: Event Consumer

- .travis.yml
This is just a suggestion but reversing the tests to let faster running ones run first will allow for a shorter feedback loop when submitting prs. Code analysers often run much faster than the actual test suite.
> Reverse order of tests

- docs/docs/getting-started/1-creating-an-aggregate-root.md
- src/AggregateRootBehaviourWithRequiredHistory.php
- src/Integration/DummyAggregateRootId.php
- src/Integration/RequiringHistoryWithAggregateRootConstruction/AggregateRootConstructionTest.php
- src/Integration/RequiringHistoryWithAggregateRootConstruction/AggregateThatRequiredHistoryForReconstitutionStub.php
- src/Integration/RequiringHistoryWithAggregateRootConstruction/DummyInternalEvent.php
- src/Integration/TestingAggregates/DummyAggregate.php
- src/Integration/TestingAggregates/ExampleAggregateRootTest.php
- src/Integration/TestingAggregates/InitiatorCommand.php
- src/InvalidAggregateRootReconstitutionException.php
This PR introduces a new aggregate root behaviour trait that forces the existence of history for an aggregate to prevent them from being instantiated without events.
/cc @asgrim Might be something for you.
> Feature: require history for reconstitution.

- phpunit.xml.dist
- src/CodeGeneration/CodeDumper.php
- src/CodeGeneration/DefinitionGroup.php
- src/CodeGeneration/Fixtures/MarkerInterfaceStub.php
- src/CodeGeneration/Fixtures/commands-with-interfaces.yaml
- src/CodeGeneration/Fixtures/commands-with-non-existing-interfaces.yaml
- src/CodeGeneration/Fixtures/commandsWithInterfaces.php
- src/CodeGeneration/Fixtures/definedWithoutHelpersInYamlFixture.php
- src/CodeGeneration/Fixtures/non-existing-interface.yaml
- src/CodeGeneration/PayloadDefinition.php
- src/CodeGeneration/YamlDefinitionLoader.php
- src/CodeGeneration/YamlDefinitionLoaderTest.php
When using commands for system interaction, a common thing is to have the identifier of the aggregate as a field in all of your commands. In order to get easier autocompletion on those fields, interfaces can be used.
Given there's an interface:
```php
interface MarkerInterfaceName {
public function id(): string;
}
```
You can generate commands and events with interfaces like this:
```yaml
---
namespace: SomeNamespace
interfaces:
marker: MarkerInterfaceName
commands:
CommandWithMarkerInterface:
implements: marker
fields:
id: string
AnotherCommandWithMarkerInterface:
implements: marker
fields:
id: string
```
Then a command handler could just accept the interface:
```php
function handle(MarkerInterfaceName $command)
{
$id = $command->id(); // Type checks out!
}
```
When using stuff like …
> Feature: codegen interfaces

- src/Message.php
- src/MessageTest.php
It makes a lot of sense to simplify the process of retrieving the time of recording, imo.
What do you think of this implementation?
> Add time of recording accessor to Message

- src/ConstructingAggregateRootRepository.php
When trying to persist an aggregate root with no pending events, it still triggers the persistence and dispatching flow.
Returning early fixes that problem.
An example of this is when you throw an exception, when a command is handled.
> fix: Avoid persisting when events are empty

- .gitattributes
Test files under `\EventSauce\EventSourcing\Snapshotting\Tests\` were being distributed with the package.
By executing `git check-attr export-ignore -- src/Snapshotting/Tests/` I get a `src/Snapshotting/Tests/: export-ignore: set`, so I think it's working.
See: https://git-scm.com/docs/git-check-attr
> Ignoring tests folders on package distribution.

- .gitignore
- .travis.yml
- composer.json
- src/Snapshotting/Tests/LightSwitch.php
This PR should provide compatibility with PHP 8. When I run the tests locally on PHP 8 in Docker they pass. 
Note that php-cs-fixer isn't patched yet so builds will fail atm (I removed the dependency locally to test). But at least this way EventSauce can already be installed on PHP 8.
Would appreciate a merge and tag so I can patch https://github.com/EventSaucePHP/LaravelEventSauce for PHP 8 :)
> PHP 8 Support

- composer.json
I'm like 99.9% sure this works this way. :) I was able to run the following command and it let me require the branch just fine. Assuming Composer rules for `branch-alias` are identical to `require`, I think this should be good to go.
```
composer require eventsauce/eventsauce:dev-version/1.0.0
```
End result after this is merged is that Packagist (and thus Composer) should allow someone to instead target 1.x:
```
composer require eventsauce/eventsauce:^1@dev
```
> Allow consumers to more easily start working with eventsauce/eventsauce:^1@dev

- .github/workflows/tests.yml
- phpstan.neon
- src/AggregateRootRepository.php
- src/AggregateRootTestCase.php
- src/ConstructingAggregateRootRepository.php
- src/EventStager.php
- src/Snapshotting/AggregateRootRepositoryWithSnapshotting.php
- src/Snapshotting/ConstructingAggregateRootRepositoryWithSnapshotting.php
This adds generics that can be used to let phpstan and psalm resolve types of returned objects from repositories.
You can now hint repositories like this:
```php
/**
* @param AggregateRootRepository<SomeAggregateRoot> $repository
*/
public function something(AggregateRootRepository $repository): void {}
```
> Generics in repositories

- src/CodeGeneration/CodeDumper.php
- src/CodeGeneration/Fixtures/definedWithYamlFixture.php
Methods generated for nullable fields are currently not nullable.
Implementation copied from https://github.com/EventSaucePHP/EventSauce/blob/version/1.0.0/src/CodeGeneration/CodeDumper.php#L115-L123
> Fix nullable return types on methods

- docs/docs/installation.md
Temporarily add notes that these packages are not compatible with EventSauce yet. See https://github.com/EventSaucePHP/DoctrineMessageRepository/pull/13
> Add notes about EventSauce v1.0 compatibility

- docs/docs/architecture.md
It seems there's no JSON based serializer in EventSauce. Only an array based one: https://github.com/EventSaucePHP/EventSauce/blob/main/src/Serialization/ConstructingMessageSerializer.php#L26
See https://github.com/EventSaucePHP/EventSauce/issues/125
> Update proper serializer type mention

- src/EventSourcedAggregateRootRepository.php
This code does not work as intended:
```php
$aggregateRootVersion = $aggregateRootVersion - count($events);
$metadata = [Header::AGGREGATE_ROOT_ID => $aggregateRootId];
$messages = array_map(fn (object $event) => $this->decorator->decorate(new Message(
$event,
$metadata + [Header::AGGREGATE_ROOT_VERSION => ++$aggregateRootVersion]
)), $events);
```
The problem here is, that short arrow function access the variables outside their scope in a by-value style. That's why each Message ends up with the same version, when calling the function once.
> Fix: EventSourcedAggregateRootRepository correctly generates version-header

- composer.json
This is the default and therefor not needed.
> Remove type from composer.json file

- composer.json
This is the default and therefor not needed.
> Remove type from composer.json

- src/EventSourcedAggregateRootRepository.php
- src/EventSourcedAggregateRootRepositoryTest.php
- src/Header.php
- src/Message.php
Discussion to see if it is feasible and desired to have Aggregate Root class name accessible from the message headers. There are a handful of places this information can be directly useful, especially when implementing a Message Repository where the underlying storage method may depend on the type of aggregate root being persisted.
Currently targeting the `main` base branch as this is possibly not a BC break and could be a part of 1.x and not just 2.x. Happy to change the base branch if `version/2.0` makes more sense.
> RFC: Include Aggregate Root class name in message headers

- docs/docs/message-storage/doctrine-2.md
The documentation page for the Doctrine V2 message repository used a `composer require` command that referenced the Doctrine V3 message repository package. This led to composer not being able to resolve to an installable set of packages. 
This MR fixes that by inserting the correct package name.
> Fix documentation: package name for Doctrine V2

- .github/workflows/publish-subsplits.yml
- src/CodeGeneration/composer.json
- src/TestUtilities/composer.json
- src/UuidMessageDecorator/composer.json
This finalizes the work started in #137 by adding branch aliases for the subsplit packages.
It also ensures the subsplit job kicks off for the `version/2.0` branch instead of just main so that the 2.x subsplit packages can exist in addition to just whatever is in `main`.
----
I don't really have the ability to test the workflow stuff since I'm not in the organization so I'm hoping this just works as-is. It *should*, but typically with changes to CI pipelines it takes me a few tries to get it right.
Desired goal:
* When this is merged, it should kick off the subsplit project for the `version/2.0` branch
* Since those projects now have the branch aliases set up we should see all three packages installable by targeting `^2`:
* `eventsauce/code-generation:^2`
* `eventsauce/test-utilities:^2` …
> Publish subsplit packages for the 2.x line and update Composer packages

- docs/docs/advanced/message-internals.md
- src/ArrayLookupClassNameInflector.php
- src/ArrayLookupClassNameInflectorTest.php
By default, the `ContructionMessageSerializer` uses the `DotSeparatedSnakeCaseInflector` to 
convert event and id class names to a string when storing an event. And to return the class from 
a string when reconstructing the event from the repository.
This couples the event's implementation details to the event storage, making it hard to refactor the Name or namespace 
of the event. (We'd have to implement our own inflector with the "changes" or update our event stream 😱 )
The `ArrayLookupClassNameInflector` could be used to declare a map from event to string.
```php
new ConstructingMessageSerializer(
new \EventSauce\EventSourcing\ArrayLookupClassNameInflector([
'TransactionRecorded' => TransactionRecorded::class
])
)
```
I think it's a good UX to include this in the package. Also happy to …
> Array lookup based class inflection

- src/LibraryConsumptionTests/ShoppingCartExample/CartItems.php
- src/LibraryConsumptionTests/ShoppingCartExample/CartItemsTest.php
- src/LibraryConsumptionTests/ShoppingCartExample/Events/CartCheckedOut.php
- src/LibraryConsumptionTests/ShoppingCartExample/Events/ProductAddedToCart.php
- src/LibraryConsumptionTests/ShoppingCartExample/Events/ShoppingCartInitiated.php
- src/LibraryConsumptionTests/ShoppingCartExample/Exceptions/SorryCantAddProduct.php
- src/LibraryConsumptionTests/ShoppingCartExample/Exceptions/SorryCantCheckout.php
- src/LibraryConsumptionTests/ShoppingCartExample/ProductId.php
- src/LibraryConsumptionTests/ShoppingCartExample/ShoppingCart.php
- src/LibraryConsumptionTests/ShoppingCartExample/ShoppingCartId.php
- src/LibraryConsumptionTests/ShoppingCartExample/ShoppingCartLifecycleTest.php
- src/LibraryConsumptionTests/ShoppingCartExample/ShoppingCartTestCase.php
I think it would be great to have a bit more "real world" example in the consumption tests. This could be used to test how certain aspects of the package work together, but more important: it shows how the package could be used.
I think it would be great to end up with one example we could use throughout the whole documentation. When maintainers agree with this idea, I'm keen on adding more complex logic, and stuff like consumers. 
It could be, that in the end, this is outside of the scope of the package. In that case, I'm more than happy to extract it to a separate repo.
> Add Shopping cart example to consumption tests

- src/TestUtilities/MessageConsumerTestCase.php
- src/TestUtilities/TestingMessageConsumers/TestedMessageConsumer.php
- src/TestUtilities/TestingMessageConsumers/TestedMessageConsumerTest.php
I find myself adding the aggregate id to messages in my consumer tests, resulting in them being less readable. (you have to construct the messages in your testcase, instead of just passing the event). 
This little helper sets the uuid of the next messages to make test classes more elegant.
```
$this
->givenNextMessagesHaveAggregateRootIdOf($aggregateRootId)
->given(
new ConsumerEvent(),
)->when(
new ConsumerEvent(),
)->then(function (TestedMessageConsumer $consumer) use ($aggregateRootId): void {
$this->assertEquals($aggregateRootId, $consumer->lastProcessedUuid());
});
```
> Message consumer testcase set aggregate id

- composer.json
- src/Serialization/MappedEventStub.php
- src/Serialization/ObjectMapperPayloadSerializer.php
- src/Serialization/ObjectMapperPayloadSerializerTest.php
- src/Serialization/PayloadSerializerSupportingObjectMapperAndSerializablePayload.php
- src/Serialization/PayloadSerializerSupportingObjectMapperAndSerializablePayloadTest.php
This serialization uses the eventsauce/object-hydrator package to map events from and to payloads. It reduces the amount of code to type significantly.
> Feature: object mapper serialization

- docs/docs/reacting-to-events/projections-and-read-models.md
- src/EventConsumer.php
- src/HandleInflector.php
- src/InflectHandlersFromClassName.php
- src/InflectHandlersFromClassNameTest.php
- src/InflectHandlersFromType.php
- src/InflectHandlersFromTypeTest.php
Building upon the features introduced with #62, this PR adds a backwards compatible strategy to determine which methods to call for an event.
The new strategy uses reflection to match the types of the methods to the event class. It enabled the uses of union types to have a single method react to multiple events.
> Feature: Event consumer strategies

- docs/docs/event-sourcing/3-configure-persistence.md
Dropped V1 indicator as all three implementations exists for V1, V2 and V3 which as this point only is overhead if all three versions would be mentioned (and possible future upkeep if/when a V4 would be released.
> Dropped V1 indicator from documentation

- docs/docs/event-sourcing/2-create-events-and-commands.md
When working on setting up EventSauce on a local POC I ran into issues as the example copied from the site didn't work.
To avoid other people from running into the same here is a small correction replacing the `SerializablePayload` with `static` as it is defined in the [interface](https://github.com/EventSaucePHP/EventSauce/blob/main/src/Serialization/SerializablePayload.php#L11)
> Correct example to match with current interface in documentation

- src/AggregateRootBehaviourWithRequiredHistory.php
In PHPStan 1.9.* we are able to use @phpstan-use to include generic traits. This is correctly done on AggregateRootBehaviour but missing on AggregateRootBehaviourWithRequiredHistory.
> Add missing template to AggregateRootBehaviourWithRequiredHistory

- src/AggregateRoot.php
See vimeo/psalm#9161 - the `@template-covariant` annotation should be applied to the AggregateRoot interface, since it should allow any covariant AggregateRootId implementation.
> Make template for AggregateRootId a covariant template

- docs/docs/advanced/anti-corruption-layer.md
- docs/docs/advanced/database-structure.md
- docs/docs/advanced/message-decoration.md
- docs/docs/architecture.md
- docs/docs/code-generation/about.md
- docs/docs/event-sourcing.md
- docs/docs/event-sourcing/2-create-events-and-commands.md
- docs/docs/event-sourcing/4-bootstrap.md
- docs/docs/index.md
- docs/docs/lifecycle.md
- docs/docs/message-outbox/setup-and-usage.md
- docs/docs/message-outbox/table-schema.md
- docs/docs/message-storage/index.md
- docs/docs/serialization/plain-serialization.md
- docs/docs/snapshotting/index.md
- docs/docs/snapshotting/setup.md
- docs/docs/testing/asserting-the-payload-of-an-event.md
- docs/docs/testing/handling-exception.md
This updates the documentation to fix some typos and minor issues with sentence structure.
> Fix typos & wording in documentation

- .github/workflows/tests.yml
Update as per https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Warnings can been seen at https://github.com/EventSaucePHP/EventSauce/actions/runs/5250334300
> ci: Update deprecated set-output command to use GITHUB environment files

- src/AggregateRootBehaviourWithRequiredHistory.php
Fixes a typo: `phstan` should be `phpstan`
> Fix typo in AggregateRootBehaviourWithRequiredHistory

- composer.json
- src/TestUtilities/composer.json
Added PHPUnit 11 as allowed version.
Locally I had some conficting phpstan errors, curious what CI thinks about it :sweat_smile:
> Allow PHPUnit 11

- docs/docs/message-storage/uuid-encoding.md
Current [title](https://eventsauce.io/docs/message-storage/uuid-encoding/) is Message Repository Table Schema, should be Uuid Encoding
> Fix Uuid encoding page title

- composer.json
- phpstan.neon
- run-tests.sh
- src/TestUtilities/AggregateRootTestCase.php
- src/TestUtilities/MessageConsumerTestCase.php
- src/TestUtilities/composer.json
Having attributes should not break for those who use old phpunit where these don't exist.
Annotations won't work anymore in PhpUnit 12.
Have used a similar approach before.
> Allow PHPUnit 12

- src/AggregateRootWithAggregates.php
The `AggregateRootWithAggregates` breaks type inference for the aggregate root's ID. When using this trait PHPStan will always infer the type as `EventSauce\EventSourcing\AggregateRootId`
For example:
```php
final class FooId implements AggregateRootId
{
public function toString(): string
{
return 'foo';
}
public static function fromString(string $aggregateRootId): static
{
return new self();
}
}
/**
* @implements AggregateRoot<FooId>
*/
final class Foo implements AggregateRoot
{
/**
* @use AggregateRootWithAggregates<FooId, EventSourcedAggregate>
*/
use AggregateRootWithAggregates;
public function weCannotInferKeyType(): void
{
dumpType($this->aggregateRootId()); // Dumped type: EventSauce\EventSourcing\AggregateRootId
}
}
```
With this PR you'd have to add `FooId` to the `@use` …
> Fix incorrect aggregate root ID type on `AggregateRootWithAggregates`

- src/CollectingMessageConsumer.php
- src/CollectingMessageDispatcher.php
Also replaced a call to `Message::event()` (which is deprecated), with `Message::payload()`
> Improve collected payload type hints
